[workspace]
resolver = "2"
members = [
    "apps/rf-android",
    "apps/web-ops",
    "crates/api",
    "crates/api-contract",
    "crates/application",
    "crates/domain",
    "crates/core",
    "crates/persistence-postgres",
    "apps/server",
    "crates/worker",
    "crates/barcodes",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.92"

[workspace.dependencies]
wareboxes-api-contract = { path = "crates/api-contract" }
wareboxes-api = { path = "crates/api" }
wareboxes-application = { path = "crates/application" }
wareboxes-domain = { path = "crates/domain" }
wareboxes-core = { path = "crates/core" }
wareboxes-barcodes = { path = "crates/barcodes" }
wareboxes-persistence-postgres = { path = "crates/persistence-postgres" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
anyhow = "1"
tracing = "0.1"
leptos = { version = "0.8" }
leptos_axum = { version = "0.8" }
leptos_meta = { version = "0.8" }
leptos_router = { version = "0.8" }

[[workspace.metadata.leptos]]
name = "wareboxes-web"
bin-package = "wareboxes-server"
bin-target = "wareboxes-server"
lib-package = "wareboxes-web-ops"
site-root = "target/site"
site-pkg-dir = "pkg"
style-file = "apps/web-ops/style/main.css"
assets-dir = "apps/web-ops/public"
site-addr = "127.0.0.1:8080"
reload-port = 3001
browserquery = "defaults"
bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false

[profile.release]
opt-level = 3
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
codegen-units = 1
panic = "abort"
