//! Transport- and persistence-independent application workflow contracts.

pub mod authorization;
pub mod backorder;
pub mod billing;
pub mod configuration;
mod context;
pub mod cross_dock;
pub mod customer_portal;
pub mod customer_return;
pub mod cycle_count;
pub mod cycle_count_control;
mod error;
pub mod facility_shipping_origin;
pub mod idempotency;
pub mod identity;
pub mod inbound_asn;
pub mod inbound_inspection;
pub mod inbound_load;
pub mod integration;
pub mod integration_mapping;
pub mod integration_monitor;
pub mod inventory;
pub mod inventory_integrity;
pub mod inventory_recall;
pub mod item_storage_policy;
pub mod item_substitution;
pub mod item_traceability_policy;
pub mod labor;
pub mod license_plate;
pub mod order_allocation;
pub mod order_amendment;
pub mod order_cancellation;
pub mod order_line_amendment;
pub mod order_release;
pub mod outbound_load;
pub mod outbound_qa;
pub mod outbox;
pub mod packing;
pub mod pick_wave;
pub mod picking;
pub mod purchase_order;
pub mod putaway;
pub mod putaway_policy;
pub mod receipt_policy;
pub mod replenishment;
pub mod service_account;
pub mod shipping;
pub mod slotting;
pub mod storage_zone;
pub mod tenant_lifecycle;
pub mod topology;
pub mod transfer_order;
pub mod value_added_work;
pub mod vendor_return;
pub mod wave_policy;
pub mod work_orchestration;
pub mod workforce_identity;
pub mod yard;

pub use context::CommandContext;
pub use error::{ApplicationError, ApplicationResult, ValidationIssue};
